version: '3'

services:
  database:
    image: 'postgres:latest'

    ports:
      - 5432:5432

    env_file:
      - .env

  web:
    build: .
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 3000:3000
    restart: always
